# Generated by Django 2.2.6 on 2019-10-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('subCategory', models.CharField(max_length=64)),
                ('vendor', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('width', models.CharField(max_length=64)),
                ('item_number', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=64)),
                ('requested_by', models.CharField(max_length=64)),
            ],
        ),
    ]
