# Generated by Django 2.2.6 on 2019-10-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0002_auto_20191022_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_id',
        ),
        migrations.AddField(
            model_name='request',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
