# Generated by Django 2.2.6 on 2019-10-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0003_auto_20191022_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='id',
        ),
        migrations.AddField(
            model_name='request',
            name='request_id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
