# Generated by Django 2.2.6 on 2019-10-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0004_auto_20191022_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_id',
            new_name='id',
        ),
    ]
