# Generated by Django 2.2.6 on 2019-10-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0006_auto_20191022_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='id',
            new_name='request_id',
        ),
    ]
