# Generated by Django 2.2.6 on 2019-10-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0008_auto_20191022_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='null', max_length=64),
        ),
    ]
