# Generated by Django 2.2.6 on 2019-10-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0010_auto_20191024_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='color',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='request',
            name='item_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='request',
            name='width',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
