# Generated by Django 2.2.6 on 2019-10-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0011_auto_20191027_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='purchaseOrder',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=200)),
                ('request', models.ForeignKey(on_delete='PROTECT', related_name='histories', to='Manager_Engine.Request')),
            ],
        ),
    ]
