# Generated by Django 2.2.6 on 2019-10-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0012_auto_20191029_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='purchaseOrder',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='subCategory',
            new_name='subcategory',
        ),
    ]
