# Generated by Django 2.2.6 on 2019-10-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0014_auto_20191029_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=16),
        ),
    ]
