# Generated by Django 2.2.6 on 2019-11-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0016_auto_20191107_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
