# Generated by Django 2.2.6 on 2019-11-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0017_auto_20191107_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.CharField(blank=True, default='0', max_length=12),
        ),
    ]
