# Generated by Django 2.2.6 on 2019-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0018_auto_20191107_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='hold_until',
            field=models.DateTimeField(default='1900-01-01', null=True),
        ),
    ]
