# Generated by Django 2.2.6 on 2019-11-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_Engine', '0019_auto_20191107_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='hold_until',
        ),
    ]
